### ISSUE TITLE
You can't relicense under NC

### ISSUE THREAD

**Issue by jtgans** [vibr77/PS2FloppyDiskAdapterWMediaSense#1]
https://creativecommons.org/licenses/by-sa/4.0/

If this really is a derivative work of my schematic, you cannot relicense it under CC-BY-SA-NC. It has to stay CC-BY-SA, and you have to attribute me on the silks, not just the readme.

**Comment by jtgans** [comment]
Bah, wrong link: https://creativecommons.org/licenses/by-sa/2.0/

Same restrictions, though. You also have to use CC-BY-SA.

**Comment by jtgans** [comment]
Also pay attention to the footnotes: https://creativecommons.org/licenses/by-sa/2.0/#ref-appropriate-credit. You need to indicate more about what you changed to the schematic than just "integrate the last missing piece to make it working".

**Comment by vibr77** [comment]
fixed
